server:
  port: 8083


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# https://www.cnblogs.com/baidawei/p/9183531.html
# auditevents beans conditions health env info metrics mappings

spring:
  application:
    name: client-hi
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        hostname: 127.0.0.1
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instance-id: ${spring.application.name}:${server.port}
        tags: ${spring.application.name}:${server.port}:${random.value}
  zipkin:
    enabled: true
    baseUrl: http://localhost:17601/ # zipkkin dashboard的地址：通过真实IP地址访问
    # 通过cloud-dashboard-zipkin注册到注册中心的服务名称访问，配置如下：
    # baseUrl: http://cloud-dashboard-zipkin/
  sleuth:
    sampler:
      probability: 1 #  默认值为0.1f，现在为了测试设置100%采集