server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7080/eureka/

spring:
  application:
    name: client-config
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: service-config