server:
  port: 8903

spring:
  application:
    name: server-turbine
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        hostname: 127.0.0.1
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instance-id: ${spring.application.name}:${server.port}
        tags: ${spring.application.name}:${server.port}:${random.value}

turbine:
  appConfig: service-feign,client-hi
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  instanceUrlSuffix: hystrix.stream

